### ISSUE TITLE
helm upgrade --install masastack masastack/masastack  error

### ISSUE THREAD

**Issue by huashao1123** [masastack/helm#3]
Events:
  Type     Reason       Age                 From     Message
  ----     ------       ----                ----     -------
  Warning  FailedMount  57m                 kubelet  Unable to attach or mount volumes: unmounted volumes=[auth-secert], unattached volumes=[kube-api-access-7d6m7 date-config auth auth-secert dapr-identity-token]: timed out waiting for the condition
  Warning  FailedMount  34m (x5 over 71m)   kubelet  Unable to attach or mount volumes: unmounted volumes=[auth-secert], unattached volumes=[auth auth-secert dapr-identity-token kube-api-access-7d6m7 date-config]: timed out waiting for the condition
  Warning  FailedMount  14m (x8 over 73m)   kubelet  Unable to attach or mount volumes: unmounted volumes=[auth-secert], unattached volumes=[dapr-identity-token kube-api-access-7d6m7 date-config auth auth-secert]: timed out waiting for the condition
  Warning  FailedMount  10s (x44 over 75m)  kubelet  MountVolume.SetUp failed for volume "auth-secert" : secret "masastack" not found

**Comment by doddgu** [comment]
@mixvii PTAL

**Comment by mixvii** [comment]
you can retry:
>  helm remove masastack   
>  helm  repo add masastack https://masastack.github.io/helm/
>  helm repo update masastack 
>  helm upgrade --install masastack masastack/masastack --version 1.0.0-rc1 --namespace masastack --create-namespace

**Comment by huashao1123** [comment]
helm remove masastack?       or  helm repo remove masastack

**Comment by mixvii** [comment]
Sorry, you're right.
helm repo remove masastack

**Comment by huashao1123** [comment]
I did it,but it is  same error also.

**Comment by huashao1123** [comment]
thanks
